name: emotionbeat
description: A Flutter app that analyzes music and user emotion.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^6.1.1
  audioplayers: ^5.2.1
  provider: ^6.1.2
  http: ^0.13.5
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1
  camera: ^0.10.5+4
  google_mlkit_face_detection: ^0.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/